# This is a basic workflow to help you get started with Actions

name: upm-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-upm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ## Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Move LICENSE and README into package
        run: |
          mv -v LICENSE.md Assets/Package/
          mv -v README.md Assets/Package/
          if [ -d Assets/Samples ]; then
            mkdir -v Assets/Package/Samples~
            mv -v Assets/Samples/* Assets/Package/Samples~/;
          fi
          git add .
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" \
            commit --author="GitHub Actions <actions@github.com>" \
            --amend --reuse-message=HEAD
      - name: Update [upm] branch and [latest] tag
        run: |
          git subtree split --prefix=Assets/Package --branch upm
          git push origin :refs/tags/latest
          git tag -f latest upm
          git push -f origin upm --tags
